name: Pull request
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: 🏗️ Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - run: yarn install

      - run: yarn lint

      - run: yarn build
